// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hhpw_be;

#nullable disable

namespace hhpw_be.Migrations
{
    [DbContext(typeof(HHPWDbContext))]
    partial class HHPWDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hhpw_be.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toblerone Cake",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Donut Shake",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chicken Hibachi",
                            Price = 18.99m
                        },
                        new
                        {
                            Id = 4,
                            Name = "California Roll",
                            Price = 24.99m
                        });
                });

            modelBuilder.Entity("hhpw_be.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerEmail = "johnny@faucet.com",
                            CustomerId = 4,
                            CustomerName = "Johnny Faucet",
                            CustomerPhone = "606-600-0006",
                            DateClosed = new DateTime(2024, 4, 15, 19, 33, 39, 68, DateTimeKind.Local).AddTicks(8622),
                            IsClosed = true,
                            OrderType = "Walk In",
                            PaymentTypeId = 1,
                            Total = 24.44m
                        },
                        new
                        {
                            Id = 2,
                            CustomerEmail = "bro@keet.com",
                            CustomerId = 3,
                            CustomerName = "Bros Keet",
                            CustomerPhone = "838-830-0006",
                            IsClosed = false,
                            OrderType = "Call In",
                            PaymentTypeId = 2,
                            Total = 56.44m
                        },
                        new
                        {
                            Id = 3,
                            CustomerEmail = "jim@jo.com",
                            CustomerId = 2,
                            CustomerName = "Jim Jo",
                            CustomerPhone = "002-387-0006",
                            DateClosed = new DateTime(2024, 4, 15, 19, 33, 39, 68, DateTimeKind.Local).AddTicks(8673),
                            IsClosed = true,
                            OrderType = "Mobile",
                            PaymentTypeId = 3,
                            Total = 93.44m
                        },
                        new
                        {
                            Id = 4,
                            CustomerEmail = "greg@gerg.com",
                            CustomerId = 1,
                            CustomerName = "Greg Gerg",
                            CustomerPhone = "499-399-0006",
                            IsClosed = false,
                            OrderType = "Call In",
                            PaymentTypeId = 1,
                            Total = 28.44m
                        });
                });

            modelBuilder.Entity("hhpw_be.Models.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Card"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PayPal"
                        });
                });

            modelBuilder.Entity("hhpw_be.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCashier")
                        .HasColumnType("boolean");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCashier = true,
                            Uid = "uid1"
                        },
                        new
                        {
                            Id = 2,
                            IsCashier = false,
                            Uid = "uid2"
                        },
                        new
                        {
                            Id = 3,
                            IsCashier = true,
                            Uid = "uid3"
                        },
                        new
                        {
                            Id = 4,
                            IsCashier = false,
                            Uid = "uid4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
